/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedItRouteImport } from './routes/_authenticated.it'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedAdminTicketsRouteImport } from './routes/_authenticated.admin.tickets'
import { Route as AuthenticatedAdminPredictionsRouteImport } from './routes/_authenticated.admin.predictions'
import { Route as AuthenticatedAdminInsightsRouteImport } from './routes/_authenticated.admin.insights'
import { Route as AuthenticatedAdminEscalatedRouteImport } from './routes/_authenticated.admin.escalated'
import { Route as AuthenticatedAdminComplianceRouteImport } from './routes/_authenticated.admin.compliance'
import { Route as AuthenticatedAdminApprovalsRouteImport } from './routes/_authenticated.admin.approvals'
import { Route as ApiPublicHooksAdminMessageFollowupRouteImport } from './routes/api/public/hooks/admin-message-followup'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedItRoute = AuthenticatedItRouteImport.update({
  id: '/it',
  path: '/it',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminTicketsRoute =
  AuthenticatedAdminTicketsRouteImport.update({
    id: '/tickets',
    path: '/tickets',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPredictionsRoute =
  AuthenticatedAdminPredictionsRouteImport.update({
    id: '/predictions',
    path: '/predictions',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminInsightsRoute =
  AuthenticatedAdminInsightsRouteImport.update({
    id: '/insights',
    path: '/insights',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEscalatedRoute =
  AuthenticatedAdminEscalatedRouteImport.update({
    id: '/escalated',
    path: '/escalated',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminComplianceRoute =
  AuthenticatedAdminComplianceRouteImport.update({
    id: '/compliance',
    path: '/compliance',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminApprovalsRoute =
  AuthenticatedAdminApprovalsRouteImport.update({
    id: '/approvals',
    path: '/approvals',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicHooksAdminMessageFollowupRoute =
  ApiPublicHooksAdminMessageFollowupRouteImport.update({
    id: '/api/public/hooks/admin-message-followup',
    path: '/api/public/hooks/admin-message-followup',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/it': typeof AuthenticatedItRoute
  '/admin/approvals': typeof AuthenticatedAdminApprovalsRoute
  '/admin/compliance': typeof AuthenticatedAdminComplianceRoute
  '/admin/escalated': typeof AuthenticatedAdminEscalatedRoute
  '/admin/insights': typeof AuthenticatedAdminInsightsRoute
  '/admin/predictions': typeof AuthenticatedAdminPredictionsRoute
  '/admin/tickets': typeof AuthenticatedAdminTicketsRoute
  '/api/public/hooks/admin-message-followup': typeof ApiPublicHooksAdminMessageFollowupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/it': typeof AuthenticatedItRoute
  '/admin/approvals': typeof AuthenticatedAdminApprovalsRoute
  '/admin/compliance': typeof AuthenticatedAdminComplianceRoute
  '/admin/escalated': typeof AuthenticatedAdminEscalatedRoute
  '/admin/insights': typeof AuthenticatedAdminInsightsRoute
  '/admin/predictions': typeof AuthenticatedAdminPredictionsRoute
  '/admin/tickets': typeof AuthenticatedAdminTicketsRoute
  '/api/public/hooks/admin-message-followup': typeof ApiPublicHooksAdminMessageFollowupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/it': typeof AuthenticatedItRoute
  '/_authenticated/admin/approvals': typeof AuthenticatedAdminApprovalsRoute
  '/_authenticated/admin/compliance': typeof AuthenticatedAdminComplianceRoute
  '/_authenticated/admin/escalated': typeof AuthenticatedAdminEscalatedRoute
  '/_authenticated/admin/insights': typeof AuthenticatedAdminInsightsRoute
  '/_authenticated/admin/predictions': typeof AuthenticatedAdminPredictionsRoute
  '/_authenticated/admin/tickets': typeof AuthenticatedAdminTicketsRoute
  '/api/public/hooks/admin-message-followup': typeof ApiPublicHooksAdminMessageFollowupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/dashboard'
    | '/it'
    | '/admin/approvals'
    | '/admin/compliance'
    | '/admin/escalated'
    | '/admin/insights'
    | '/admin/predictions'
    | '/admin/tickets'
    | '/api/public/hooks/admin-message-followup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin'
    | '/dashboard'
    | '/it'
    | '/admin/approvals'
    | '/admin/compliance'
    | '/admin/escalated'
    | '/admin/insights'
    | '/admin/predictions'
    | '/admin/tickets'
    | '/api/public/hooks/admin-message-followup'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/it'
    | '/_authenticated/admin/approvals'
    | '/_authenticated/admin/compliance'
    | '/_authenticated/admin/escalated'
    | '/_authenticated/admin/insights'
    | '/_authenticated/admin/predictions'
    | '/_authenticated/admin/tickets'
    | '/api/public/hooks/admin-message-followup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiPublicHooksAdminMessageFollowupRoute: typeof ApiPublicHooksAdminMessageFollowupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/it': {
      id: '/_authenticated/it'
      path: '/it'
      fullPath: '/it'
      preLoaderRoute: typeof AuthenticatedItRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/tickets': {
      id: '/_authenticated/admin/tickets'
      path: '/tickets'
      fullPath: '/admin/tickets'
      preLoaderRoute: typeof AuthenticatedAdminTicketsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/predictions': {
      id: '/_authenticated/admin/predictions'
      path: '/predictions'
      fullPath: '/admin/predictions'
      preLoaderRoute: typeof AuthenticatedAdminPredictionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/insights': {
      id: '/_authenticated/admin/insights'
      path: '/insights'
      fullPath: '/admin/insights'
      preLoaderRoute: typeof AuthenticatedAdminInsightsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/escalated': {
      id: '/_authenticated/admin/escalated'
      path: '/escalated'
      fullPath: '/admin/escalated'
      preLoaderRoute: typeof AuthenticatedAdminEscalatedRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/compliance': {
      id: '/_authenticated/admin/compliance'
      path: '/compliance'
      fullPath: '/admin/compliance'
      preLoaderRoute: typeof AuthenticatedAdminComplianceRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/approvals': {
      id: '/_authenticated/admin/approvals'
      path: '/approvals'
      fullPath: '/admin/approvals'
      preLoaderRoute: typeof AuthenticatedAdminApprovalsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/hooks/admin-message-followup': {
      id: '/api/public/hooks/admin-message-followup'
      path: '/api/public/hooks/admin-message-followup'
      fullPath: '/api/public/hooks/admin-message-followup'
      preLoaderRoute: typeof ApiPublicHooksAdminMessageFollowupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminApprovalsRoute: typeof AuthenticatedAdminApprovalsRoute
  AuthenticatedAdminComplianceRoute: typeof AuthenticatedAdminComplianceRoute
  AuthenticatedAdminEscalatedRoute: typeof AuthenticatedAdminEscalatedRoute
  AuthenticatedAdminInsightsRoute: typeof AuthenticatedAdminInsightsRoute
  AuthenticatedAdminPredictionsRoute: typeof AuthenticatedAdminPredictionsRoute
  AuthenticatedAdminTicketsRoute: typeof AuthenticatedAdminTicketsRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminApprovalsRoute: AuthenticatedAdminApprovalsRoute,
  AuthenticatedAdminComplianceRoute: AuthenticatedAdminComplianceRoute,
  AuthenticatedAdminEscalatedRoute: AuthenticatedAdminEscalatedRoute,
  AuthenticatedAdminInsightsRoute: AuthenticatedAdminInsightsRoute,
  AuthenticatedAdminPredictionsRoute: AuthenticatedAdminPredictionsRoute,
  AuthenticatedAdminTicketsRoute: AuthenticatedAdminTicketsRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedItRoute: typeof AuthenticatedItRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedItRoute: AuthenticatedItRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiPublicHooksAdminMessageFollowupRoute:
    ApiPublicHooksAdminMessageFollowupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
